name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install iminuit flake8 black isort
      - name: Code quality checks
        run: |
          isort --check --diff ./kafe2
          black --check --diff ./kafe2
          flake8 --config .flake8 ./kafe2
