# This workflows will upload a Python Package using Twine when a release is published
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package (manual)

on: workflow_dispatch


jobs:
  deploy:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

    - name: Setup build environment 
      run: |
        python -m pip install --upgrade build twine

    - name: Build source and wheel distributions
      run: |
        python -m build
        twine check --strict dist/*

    - name: Publish to PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload --verbose dist/*
